In [ ]:
# 1.Real, complex,scalar

In [3]:
import numpy as np

In [53]:
arr = (np.random.random(20) * 5).reshape(4,5)
print('Array:',arr)
print('_'*80)
print('Real:',arr[np.isreal(arr)])
print('_'*80)
print('Complex:',arr[np.iscomplex(arr)])

Array: [[3.94692767 3.97951295 4.57063303 1.04680778 0.66616271]
 [0.35560174 0.4635234  4.07890073 4.60642292 4.96060029]
 [4.98801458 2.52644771 3.04632747 1.29564683 2.96368493]
 [1.90427514 1.83298758 3.70930129 3.10923057 4.49587359]]
________________________________________________________________________________
Real: [3.94692767 3.97951295 4.57063303 1.04680778 0.66616271 0.35560174
 0.4635234  4.07890073 4.60642292 4.96060029 4.98801458 2.52644771
 3.04632747 1.29564683 2.96368493 1.90427514 1.83298758 3.70930129
 3.10923057 4.49587359]
________________________________________________________________________________
Complex: []


In [62]:
scalar = []
for i in arr:
    scalar.append(np.isscalar(i))
print('Scalars in array:',scalar)

scalar_lst = []
for i in arr:
    for j in i:
        scalar_lst.append(np.isscalar(j))
print('Scalars in array lists:',scalar_lst)

Scalars in array: [False, False, False, False]
Scalars in array lists: [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]


In [ ]:
# 2.Element-wise comparison

In [63]:
arr_1 = np.random.randint(1,100,20)
arr_2 = np.random.randint(20,120,20)
print('Array_1:',arr_1)
print('_' * 100)
print('Array_2:',arr_2)
print('_' * 100)
print('Equal:',np.equal(arr_1,arr_2))
print('_' * 100)
print('Greater:',np.greater(arr_1,arr_2))
print('_' * 100)
print('Greater equal:',np.greater_equal(arr_1,arr_2))
print('_' * 100)
print('Less:',np.less(arr_1,arr_2))
print('_' * 100)
print('Less equal:',np.less_equal(arr_1,arr_2))

Array_1: [21 80 22 61 73 88  2 58 93 15 17 45 26 49 49 33 80 21 26 72]
____________________________________________________________________________________________________
Array_2: [ 98  30 105  70 107  50  74  65  31  68  85 114 115  84 114  46  92 118
  86  64]
____________________________________________________________________________________________________
Equal: [False False False False False False False False False False False False
 False False False False False False False False]
____________________________________________________________________________________________________
Greater: [False  True False False False  True False False  True False False False
 False False False False False False False  True]
____________________________________________________________________________________________________
Greater equal: [False  True False False False  True False False  True False False False
 False False False False False False False  True]
_________________________________

In [63]:
# 3.NumPy array of 10 zeros,10 ones, 10 fives.

In [71]:
arr_1 = np.zeros(10)
arr_2 = np.ones(10)
arr_3 = np.zeros(10)
arr_3.fill(5)

array = np.asarray((arr_1,arr_2,arr_3), dtype = float)
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [ ]:
# 4.Update 6th number

In [64]:
vec = np.zeros(10)
vec[5] = 11
print(vec)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [ ]:
# 5.Array from normal distribution 

In [69]:
normal_arr = np.random.normal(1,1,(5,5))
print('Normal distributed array:\n',normal_arr)
print('_'*70)
print('Reversed array:\n',np.flip(normal_arr))

Normal distributed array:
 [[ 1.49507935  0.84278885  1.68044865  1.49461918  1.90937238]
 [ 0.79488176  0.01469364  0.48649149  1.21982902  0.75839408]
 [ 0.41322533  1.48758463  0.26875677  2.81579428  0.52938124]
 [ 1.13824116 -0.1904366   0.92060983  0.03172401  0.84546444]
 [-0.22791434  0.62417794 -1.00765087  1.84973255  1.19623118]]
______________________________________________________________________
Reversed array:
 [[ 1.19623118  1.84973255 -1.00765087  0.62417794 -0.22791434]
 [ 0.84546444  0.03172401  0.92060983 -0.1904366   1.13824116]
 [ 0.52938124  2.81579428  0.26875677  1.48758463  0.41322533]
 [ 0.75839408  1.21982902  0.48649149  0.01469364  0.79488176]
 [ 1.90937238  1.49461918  1.68044865  0.84278885  1.49507935]]


In [ ]:
# 6.Borders

In [117]:
arr_ones = np.ones(9).reshape(3,3)
print(arr_ones)
border = np.pad(arr_ones,1)
print(border)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [118]:
# 7.Checkerbord pattern

In [133]:
arr = np.zeros(64, dtype = int).reshape(8,8)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 8.Centigrade to Fahrenheit

In [70]:
arr = np.random.random(20) * 30
arr_fahrenheit = arr * 9/5 +50 
print('Centigrade array:\n',arr)
print('_'*80)
print('Fahrenheit array:\n',arr_fahrenheit)

Centigrade array:
 [24.98120456  7.17332889 20.15936072  6.73067761 20.85405736 14.97942592
 23.09816092 19.17322886  3.56925702 15.04331033  8.6147361  27.60637672
 27.13531583 10.56381855 11.24557991 16.97347126 11.55021329 25.51485801
 21.32147374 18.23745642]
________________________________________________________________________________
Fahrenheit array:
 [94.96616821 62.91199199 86.28684929 62.1152197  87.53730324 76.96296665
 91.57668966 84.51181194 56.42466263 77.0779586  65.50652499 99.69147809
 98.8435685  69.01487339 70.24204384 80.55224827 70.79038391 95.92674441
 88.37865273 82.82742156]


In [1]:
# 9.Two arrays

In [76]:
arr_1 = np.random.randint(0,50,10)
arr_2 = np.random.randint(0,50,10)
print('Array 1:',arr_1)
print('Array 2:',arr_2)
check = []
for i in range(len(arr_1)):
    if arr_1[i] in arr_2:
        check.append(True)
    else:
        check.append(False)
print(check)

Array 1: [37 15 24  8 22 30 35 47 27 31]
Array 2: [14 49 13 22 32 32 44 31 45 28]
[False, False, False, False, True, False, False, False, False, True]


In [75]:
# Equal values

In [40]:
arr_1 = np.random.randint(0,20,10)
arr_2 = np.random.randint(0,20,10)
print('Array 1:',arr_1)
print('Array 2:',arr_2)
equal = []
for i in range(len(arr_1)):
    if arr_1[i] in arr_2:
        equal.append(arr_1[i])
print('Equal values:',set(equal))

Array 1: [15 13  9  8 10 10  5  7  1  3]
Array 2: [13 10  7  7  3  2 12 17  5 13]
Equal values: {3, 5, 7, 10, 13}
