In [1]:
import numpy as np

1. Ստեղծել np զանգված, որը կպարունակի 100 պատահական ամբողջ թիվ։ Այնուհետև ստանալ այն տարրերի ինդեքսները, որոնք ավարտվում են 6-ով։

In [2]:
arr = np.random.randint(0, 100, 100)
index = np.where(arr%10 == 6 )
print(arr)
print(index)
print(arr[index])

[42 94 41 87 93 60 27 41  1 99 79 85 49 21 82 67 83  6 16 58 41  6 58  6
 98 67 24 27 24 88 67 24 49 99  2 65 62  8 43 86 86 52 49 77  4 64 84 79
 36  4 45 33 66 78 50 11 25 75 90 28 73 14 15 35 53 47 91 33 50 29 60 81
 47 42 43 76 65 44 13 17 77 66 73 82 17 83 72  3  6 15 62 21 56 38 89 34
 55 47  7 34]
(array([17, 18, 21, 23, 39, 40, 48, 52, 75, 81, 88, 92], dtype=int64),)
[ 6 16  6  6 86 86 36 66 76 66  6 56]


2. Ստեղծել np զանգված, որի բոլոր տարրերը կլինեն 0-ներ, իսկ անկյունագծայինները՝ 1։

In [3]:
arr = np.zeros((3,3), dtype = int)
np.fill_diagonal(arr, 1)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


3. Ստեղծել երկու np միաչափ զանգված արդեն պատրաստի պիտոնական լիստերից (հիշեցում․ asarray, array)։ Ապա կցեք երկու զանգվածներն իրար հորիզոնական ուղությամբ։ 

օրինակ, եթե
```python
import numpy as np

arr_1 -> array([1, 2, 3])
arr_2 -> array([4, 5, 6])

```
ապա արդյունքը պետք է լինի
```python
array([1, 2, 3, 4, 5, 6])
```

In [4]:
arr_1 = np.array([1,2,3])
arr_2 = np.asarray([4,5,6])
np.hstack((arr_1,arr_2))

array([1, 2, 3, 4, 5, 6])

4. Ստեղծել երկու np միաչափ զանգված արդեն պատրաստի պիտոնական լիստերից (հիշեցում․ asarray, array)։ Ապա կցեք երկու զանգվածներն իրար վերտիկալ ուղությամբ։ 

օրինակ, եթե
```python
import numpy as np

arr_1 -> array([1, 2, 3])
arr_2 -> array([4, 5, 6])

```
ապա արդյունքը պետք է լինի
```python
array([[1, 2, 3],
       [4, 5, 6]])
```

In [5]:
np.vstack((arr_1,arr_2))

array([[1, 2, 3],
       [4, 5, 6]])

5. Ստեղծել երկչափ զանգված, որը կունենա (3, 3) shape: Այնուհետև ստեղծել նոր զանգված, որը կլինի նախորդ զանգվածը, սակայն առաջին և երրորդ սյուների տեղերը փոխած։

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr_re = arr.reshape(3, 3)
print(arr_re)
for i in range(len(arr_re)):
    arr_re[i][0],arr_re[i][2] = arr_re[i][2],arr_re[i][0]
print(arr_re)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


6.  Ստեղծել երեք զանգված։ Առաջինը պետք է պարունակի միայն 0-ներ, երկրորդը միայն 1-եր, իսկ երրորդը միայն 9-եր։

In [7]:
arr_1 = np.zeros((4,4), dtype=int)
arr_2 = np.ones((4,4), dtype = int)
arr_3 = np.zeros((4,4), dtype=int)
arr_3.fill(9)
print(arr_1)
print(arr_2)
print(arr_3)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


7. Ստեղծել (10, 10) shape-ով զանգված։ Ապա փոխել դրա shape-ը հնարավոր բոլոր տարբերակներով։ 

In [8]:
arr = np.arange(10)
arr_1 = arr.reshape(5,2)
arr_2 = arr.reshape(2,5)
arr_3 = arr.reshape(1,10)
arr_4 = arr.reshape(10,1)
print(arr_1)
print(arr_2)
print(arr_3)
print(arr_4)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


8. Ստեղծել երկու երկչափ զանգված և հաշվել դրանց ա) տարր առ տարր արտադրյալը, բ) մատրիցային արտադրյալը։

In [9]:
arr_1 = np.arange(9).reshape(3,3)
arr_2 = np.arange(10,19).reshape(3,3)

print(np.multiply(arr_1,arr_2))
print(np.dot(arr_1,arr_2))

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
[[ 45  48  51]
 [162 174 186]
 [279 300 321]]



9. Ստեղծել երկու զանգված (10, 10) shape-ի, որոնք կպարունակեն 0-ից 20-ը պատահական թվեր։ Բաժանել մատրիցներն իրար։ Այնուհետև առանձնացնել նոր մատրիցի մեջ մատրիցների այն տարրերը, որոնք թիվ են (inf կամ nan չեն): Ստանալ inf-երի և nan-երի նաև դրանց ինդեքսները։

In [10]:
a = np.random.randint(0,20,100).reshape(10,10)
b = np.random.randint(0,20,100).reshape(10,10)
c = np.divide(b,a)

c[np.where((c != np.inf) & (c != np.nan))]

<ipython-input-10-fa04183f27e5>:3: RuntimeWarning: divide by zero encountered in true_divide
  c = np.divide(b,a)


array([ 0.375     ,  0.        ,  2.83333333,  1.54545455,  2.        ,
        0.25      ,  1.7       ,  1.14285714,  0.75      ,  4.33333333,
        0.6       ,  1.5       ,  0.875     ,  1.        ,  7.        ,
        5.        ,  1.11111111,  0.41666667,  1.9       ,  4.75      ,
        0.3125    ,  0.        ,  0.        ,  0.27272727,  0.38888889,
        0.        ,  0.26315789,  0.1875    ,  1.11764706,  4.5       ,
        4.75      ,  1.09090909,  3.        ,  1.75      ,  1.        ,
        2.        ,  0.63157895,  0.61111111,  1.8       ,  0.1875    ,
        0.4       ,  1.        ,  1.        ,  0.5       ,  0.        ,
        0.18181818,  0.        ,  1.72727273,  0.41176471,  0.5       ,
        0.        ,  0.47368421,  1.15384615,  4.        ,  2.33333333,
        0.30769231,  0.3       ,  1.26666667,  0.63157895,  0.94736842,
        0.25      ,  0.5       ,  1.66666667,  1.33333333,  7.5       ,
        2.4       ,  0.18181818,  1.42857143,  0.30769231,  1.5 

10. Ստեղծել (3, 3) մատրից, որի տարրերը կլինեն 11-19, սակայն բացահայտ կերպով սահմանել տարրերի տիպը որպես float։

In [11]:
arr = np.arange(11,20,dtype=float).reshape(3,3)
print(arr)

[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]


11.Ստեղծել (10,10) ռանդոմ մատրից, հաշվել սյուների միջին արժեքները։

In [12]:
arr = np.random.randint(0,10,100).reshape(10,10)
print(arr)
s = 0
np.mean(arr,axis=0)

[[2 8 6 3 4 5 0 8 0 5]
 [6 6 4 1 8 7 8 2 0 2]
 [2 4 2 8 5 4 9 4 5 8]
 [2 0 2 6 4 5 4 1 1 2]
 [6 7 5 1 8 9 0 5 0 9]
 [9 1 8 1 0 8 4 9 7 6]
 [9 0 9 8 5 8 8 9 3 2]
 [7 5 3 2 9 0 0 4 9 8]
 [9 4 1 5 8 5 5 7 6 3]
 [2 9 9 3 1 3 0 4 1 9]]


array([5.4, 4.4, 4.9, 3.8, 5.2, 5.4, 3.8, 5.3, 3.2, 5.4])